// @generated by aitc build-root; do not edit by hand.
use std::cell::RefCell;
use std::sync::Arc;

#[derive(Default)]
struct Assembly {
    copyqueue: RefCell<Option<Arc<dyn copyqueue::CopyQueue>>>,
    copyqueue_copyscheduler: RefCell<Option<Arc<dyn copyqueue_copyscheduler::CopyScheduler>>>,
    output: RefCell<Option<Arc<dyn output::Output>>>,
    snapshot: RefCell<Option<Arc<dyn snapshot::Snapshot>>>,
    snapshot_clock: RefCell<Option<Arc<dyn snapshot_clock::Clock>>>,
    transport: RefCell<Option<Arc<dyn transport::Transport>>>,
}

impl Assembly {
    fn get_cli(&self) -> Arc<dyn cli::Cli> { cli::new() }
    fn get_copyqueue(&self) -> Arc<dyn copyqueue::CopyQueue> {
        if let Some(existing) = self.copyqueue.borrow().as_ref() {
            return existing.clone();
        }
        let built = copyqueue::new(self.get_transport(), self.get_output());
        *self.copyqueue.borrow_mut() = Some(built.clone());
        built
    }
    fn get_copyqueue_copyscheduler(&self) -> Arc<dyn copyqueue_copyscheduler::CopyScheduler> {
        if let Some(existing) = self.copyqueue_copyscheduler.borrow().as_ref() {
            return existing.clone();
        }
        let built = copyqueue_copyscheduler::new();
        *self.copyqueue_copyscheduler.borrow_mut() = Some(built.clone());
        built
    }
    fn get_copyqueue_stagingcleanup(&self) -> Arc<dyn copyqueue_stagingcleanup::StagingCleanup> { copyqueue_stagingcleanup::new() }
    fn get_copyqueue_swaptransfer(&self) -> Arc<dyn copyqueue_swaptransfer::SwapTransfer> { copyqueue_swaptransfer::new() }
    fn get_output(&self) -> Arc<dyn output::Output> {
        if let Some(existing) = self.output.borrow().as_ref() {
            return existing.clone();
        }
        let built = output::new();
        *self.output.borrow_mut() = Some(built.clone());
        built
    }
    fn get_runcontroller(&self) -> Arc<dyn runcontroller::RunController> { runcontroller::new(self.get_cli(), self.get_transport(), self.get_snapshot(), self.get_syncengine(), self.get_copyqueue(), self.get_output()) }
    fn get_snapshot(&self) -> Arc<dyn snapshot::Snapshot> {
        if let Some(existing) = self.snapshot.borrow().as_ref() {
            return existing.clone();
        }
        let built = snapshot::new(self.get_transport());
        *self.snapshot.borrow_mut() = Some(built.clone());
        built
    }
    fn get_snapshot_clock(&self) -> Arc<dyn snapshot_clock::Clock> {
        if let Some(existing) = self.snapshot_clock.borrow().as_ref() {
            return existing.clone();
        }
        let built = snapshot_clock::new();
        *self.snapshot_clock.borrow_mut() = Some(built.clone());
        built
    }
    fn get_snapshot_identity(&self) -> Arc<dyn snapshot_identity::Identity> { snapshot_identity::new() }
    fn get_snapshot_store(&self) -> Arc<dyn snapshot_store::Store> { snapshot_store::new(self.get_snapshot_clock(), self.get_snapshot_identity()) }
    fn get_snapshot_transfer(&self) -> Arc<dyn snapshot_transfer::Transfer> { snapshot_transfer::new() }
    fn get_syncengine(&self) -> Arc<dyn syncengine::SyncEngine> { syncengine::new(self.get_copyqueue(), self.get_output(), self.get_snapshot(), self.get_transport()) }
    fn get_syncengine_decisionrules(&self) -> Arc<dyn syncengine_decisionrules::DecisionRules> { syncengine_decisionrules::new() }
    fn get_syncengine_displacement(&self) -> Arc<dyn syncengine_displacement::Displacement> { syncengine_displacement::new() }
    fn get_transport(&self) -> Arc<dyn transport::Transport> {
        if let Some(existing) = self.transport.borrow().as_ref() {
            return existing.clone();
        }
        let built = transport::new();
        *self.transport.borrow_mut() = Some(built.clone());
        built
    }
    fn get_transport_localbackend(&self) -> Arc<dyn transport_localbackend::LocalBackend> { transport_localbackend::new() }
    fn get_transport_sftpbackend(&self) -> Arc<dyn transport_sftpbackend::SftpBackend> { transport_sftpbackend::new() }
    fn get_transport_urlnormalize(&self) -> Arc<dyn transport_urlnormalize::UrlNormalize> { transport_urlnormalize::new() }
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let assembly = Assembly::default();
    let cli = assembly.get_cli();
    match cli.parse(args) {
        cli::CliOutcome::Help => {
            print!("{}", cli.help_text());
            std::process::exit(0);
        }
        cli::CliOutcome::Reject(msg) => {
            print!("{}\n{}", msg, cli.help_text());
            std::process::exit(1);
        }
        cli::CliOutcome::Run(config) => {
            let outcome = assembly.get_runcontroller().run(config);
            if let Some(msg) = outcome.message {
                println!("{}", msg);
            }
            std::process::exit(outcome.exit_code);
        }
    }
}
