#!/usr/bin/env uvrun
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""TEST-EASY — mechanically generated by aitc Build. Do not hand-edit;
the next Build invocation overwrites this file from the wrapper's
tools/list."""

from __future__ import annotations

import json
import os
import re
import socket
import subprocess
import sys
import threading
import time
from pathlib import Path

BUILD_PY = Path(os.environ.get("AITC_BUILD_PY", "/home/ace/Desktop/prjx/kitchensync/aitc/languages/java/build.py"))
UV = Path(os.environ.get("AITC_UV", "aitc/bin/uv.linux"))
PROJECT = os.environ.get("AITC_PROJECT_PATH", ".")

EXPECTED_COUNT = 1
STUB_CALLS = [["run", {"args": []}]]


KEBAB_RE = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*$")


def _drain(stream):
    try:
        for _ in stream:
            pass
    except Exception:
        pass


def _launch():
    proc = subprocess.Popen(
        [str(UV), "run", "--script", str(BUILD_PY), "launch-mcp", PROJECT],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
    )
    port = None
    deadline = time.time() + 30
    while time.time() < deadline and proc.poll() is None:
        line = proc.stdout.readline()
        if not line:
            continue
        line = line.strip()
        if line.startswith("MCP_PORT="):
            try:
                port = int(line.split("=", 1)[1])
            except ValueError:
                pass
            break
    if port is None:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
        raise RuntimeError("MCP server did not advertise MCP_PORT")
    threading.Thread(target=_drain, args=(proc.stdout,), daemon=True).start()
    threading.Thread(target=_drain, args=(proc.stderr,), daemon=True).start()
    return proc, port


def _rpc(sock, method, params=None, rpc_id=1):
    msg = {"jsonrpc": "2.0", "id": rpc_id, "method": method}
    if params is not None:
        msg["params"] = params
    sock.sendall((json.dumps(msg) + "\n").encode("utf-8"))
    buf = b""
    deadline = time.time() + 10
    while time.time() < deadline:
        chunk = sock.recv(8192)
        if not chunk:
            break
        buf += chunk
        if b"\n" in buf:
            break
    line, _, _ = buf.partition(b"\n")
    if not line:
        return {}
    return json.loads(line.decode("utf-8"))


def main() -> int:
    proc, port = _launch()
    failures: list[str] = []
    try:
        with socket.create_connection(("127.0.0.1", port), timeout=10) as s:
            tl = _rpc(s, "tools/list")
            tools = (tl.get("result") or {}).get("tools", [])
            names = [t.get("name", "") for t in tools]

            print(f"[01] tools/list returned {len(tools)} tool(s) "
                  f"(expected {EXPECTED_COUNT})")
            if len(tools) != EXPECTED_COUNT:
                failures.append(
                    f"01: tool count mismatch — got {len(tools)}, "
                    f"expected {EXPECTED_COUNT}"
                )

            print(f"[02] kebab-case check on {len(names)} name(s)")
            non_kebab = [n for n in names if not KEBAB_RE.match(n)]
            if non_kebab:
                failures.append(f"02: non-kebab tool names: {non_kebab}")

            print("[03] alphabetical-sort check")
            if names != sorted(names):
                failures.append("03: tools/list is not alphabetically sorted")

            for i, (name, args) in enumerate(STUB_CALLS, start=4):
                resp = _rpc(
                    s, "tools/call",
                    {"name": name, "arguments": args},
                    rpc_id=i,
                )
                err = resp.get("error")
                if err:
                    print(f"[{i:02d}] {name}: ERROR {err}")
                    failures.append(
                        f"{i:02d}: {name} returned JSON-RPC error: {err}"
                    )
                else:
                    print(f"[{i:02d}] {name}: ok")

        if failures:
            print()
            print("FAILURES:")
            for f in failures:
                print(f"  - {f}")
            return 1
        print()
        print("All assertions passed.")
        return 0
    finally:
        try:
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait()
        except Exception:
            pass


if __name__ == "__main__":
    sys.exit(main())
